# Generated by Django 3.2.11 on 2022-02-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulupulang', '0005_make_datetimefields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text="This should be your email address. Make sure it's a valid email address and that you have access to it.", max_length=128, verbose_name='Email address'),
        ),
    ]
