# Generated by Django 3.2.11 on 2022-02-08 17:48

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('kulupulang', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='this is your email address. make sure you have access to it!', max_length=128, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='this name will appear on the site in place of your username. leave it blank to revert to your username being used across the site.', max_length=64, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, help_text='this is the unique identifier you will to log in. it may only contain letters and numbers.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
