# Generated by Django 3.2.11 on 2022-02-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulupulang', '0007_auto_20220208_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='default', help_text='the theme you want to display the site in', max_length=64),
        ),
    ]
