# Generated by Django 3.2.11 on 2022-02-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulupulang', '0008_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='hours_left_before_discussion',
            field=models.IntegerField(default=0),
        ),
    ]
