# Generated by Django 3.2.11 on 2022-02-09 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulupulang', '0009_batch_hours_left_before_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='batch_contribution_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
