# Generated by Django 3.2.17 on 2023-02-06 21:39

from django.db import migrations, models


def add_themes(apps, schema_editor):
    Theme = apps.get_model("kulupulang", "Theme")
    Theme.objects.create(
        name="default",
        description=(
            "the beautiful if a little flashy default theme in pink. "
            "it's the absolute pride of makkulu. all must love the "
            "pink! it is commanded of us!"
        ),
        css="default.theme.css",
    )
    Theme.objects.create(
        name="digital",
        description=(
            "do you live a high-tech high-speed high-stakes kind of "
            "a lifestyle? you want this little website to reflect "
            "that for you? of course you do. pick me then, squirt."
        ),
        css="digital.theme.css",
    )
    Theme.objects.create(
        name="mint",
        description=(
            "ah yes, i see you. you like the finer things in life. "
            "romance by the fireplace, songs by the hearth. needle-"
            "pointing and crocheting. come, sit a while. enjoy the "
            "mint breeze."
        ),
        css="mint.theme.css",
    )
    Theme.objects.create(
        name="windows",
        description=(
            "michaelsoft wimblows eggs-dee is the newest and latest "
            "state of the art operating syst- uh, i mean, theme. "
            "honestly, check it out."
        ),
        css="windows.theme.css",
        external_css="https://unpkg.com/xp.css",
    )


def remove_themes(apps, schema_editor):
    Theme = apps.get_model("kulupulang", "Theme")
    Theme.objects.filter(name="default").delete()
    Theme.objects.filter(name="digital").delete()
    Theme.objects.filter(name="mint").delete()
    Theme.objects.filter(name="windows").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("kulupulang", "0010_alter_batch_contributors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("css", models.CharField(max_length=255)),
                ("external_css", models.TextField(blank=True, null=True)),
                ("external_js", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(add_themes, reverse_code=remove_themes),
    ]
