# Generated by Django 3.2.17 on 2023-02-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kulupulang', '0011_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.ForeignKey(default=1, help_text='the theme you want to display the site in', on_delete=django.db.models.deletion.SET_DEFAULT, to='kulupulang.theme'),
        ),
    ]
